Restrições hard:
Não podemos alocar uma turma numa sala com quantidade de assentos menor
que o número de alunos matriculados.
Não podemos alocar uma turma que necessita de acessibilidade numa sala que
não é acessível
Restrições soft
• Devemos minimizar a taxa de ocupação de salas: (número de alunos
– tamanho da sala)/tamanho da sala.
• Restrição de qualidade da sala: Uma turma de qualidade baixa pode
ser alocada numa sala de qualidade alta, mas o contrário não é
verdade.
• Restrição de salas no mesmo horário: penalizar uma distribuição
onde uma mesma turma esteja numa sala diferentes.
• Restrição de calouros na mesma sala: penalizar distribuições onde
turmas de calouros de um mesmo curso estejam em salas
diferentes.

In [39]:
import csv
from typing import Dict,List
from queue import Queue
import numpy as np

def transHorario(horario):
    list = []
    turmaTemp = horario.split("-")
    for i in range(len(turmaTemp)):
        dia = int(turmaTemp[i][0])
        turno = turmaTemp[i][1]
        horarioIni = int(turmaTemp[i][2])

        if(turno == 'T'):
            horarioIni = horarioIni +3

        elif(turno == 'N'):
            horarioIni = horarioIni + 6
        '''
        if(int(turmaTemp[i][0]) == 2):
            dia = 'seg'
        elif(int(turmaTemp[i][0]) == 3):
            dia = 'ter'
        elif(int(turmaTemp[i][0]) == 4):
            dia = 'qua'
        elif(int(turmaTemp[i][0]) == 5):
            dia = 'qui'
        elif(int(turmaTemp[i][0]) == 6):
            dia = 'sex'
        else:
            dia = 'sab'
        '''
        list.append((dia,int(horarioIni)))
    return list


    
df = csv.DictReader(open(r"C:\Users\Paulo\Desktop\Trabalho SAD\cenario1-salas.csv",encoding='utf-8'))
salas = []
id_salas = [] 
for row in df:
    salas[row['id_sala']] = {"cad": row['numero_cadeiras'], "acess": row['acessivel'], "quali": row['qualidade']}
    id_salas.append(row['id_sala'])



df = csv.DictReader(open(r"C:\Users\Paulo\Desktop\Trabalho SAD\cenario1-turmas.csv",encoding='utf-8'))
turmas = []
for row in df:
    turmas.append({"disc" :row['disciplina'],"prof": row['professor'], "horario": transHorario(row['dias_horario']),
                                "alunos": int(row['numero_alunos']),"curso": row['curso'],"periodo": int(row['período'])
                                ,"acess": int(row['acessibilidade']),"qual": int(row['qualidade'])})


 
'''
for sala in salas:
    print(sala)

for turma in turmas:
    print(turma)
'''
horarios = []
for sala in id_salas:
    horarios[sala] =  {"seg":{"1": 0, "2": 0 , "3": 0 , "4": 0, "5": 0 , "6": 0 ,"7": 0 ,"8": 0 },
                                  "ter":{"1": 0, "2": 0 , "3": 0 , "4": 0 , "5": 0 , "6": 0 ,"7": 0 ,"8": 0 },
                                  "qua":{"1": 0, "2": 0 , "3": 0 , "4": 0 , "5": 0 , "6": 0 ,"7": 0 ,"8": 0 },
                                  "qui":{"1": 0, "2": 0 , "3": 0 , "4": 0 , "5": 0 , "6": 0 ,"7": 0 ,"8": 0 },
                                  "sex":{"1": 0, "2": 0 , "3": 0 , "4": 0 , "5": 0 , "6": 0 ,"7": 0 ,"8": 0 },
                                 "sab":{"1": 0, "2": 0 , "3": 0 , "4": 0 , "5": 0 , "6": 0 ,"7": 0 ,"8": 0 }}



TypeError: list indices must be integers or slices, not str

um dict para dia/horario/sala 

In [34]:

def encontraMelhorSala(turma,dia,horario,salas,matriz):
    i = 0
    matriz[dia-2][horario-1][i] = 1 + matriz[dia-2][horario-1][i]
    '''
    while(True):
        #if(matriz[dia-2][horario-1][i] == 0 and salas[i]['cad'] >= turma['alunos']):
            #print("alocado",dia,horario,turma['disc'],salas[i]['id'])
            #matriz[dia-2][horario-1][i] = 1 + matriz[dia-2][horario-1][i]
        break
        if(i == len(salas)-1):
            i = 0
        else:
            i += 1
    '''
turmas = sorted(turmas, key=lambda turma: turma['alunos'])
salas = sorted(salas, key=lambda sala: sala['cad'])


conflitos = 0 
for i in range (len(turmas)):
    for j in range(len(turmas)):
        if(turmas[i]['horario'] == turmas[j]['horario']):
            conflitos =conflitos +1
print(conflitos)
matriz = np.zeros((6,9,len(salas))) 
t = Queue(len(turmas))
s = Queue(len(salas))
for i in range(len(salas)):
    s.put(salas[i])
    
for i in range(len(turmas)):
    t.put(turmas[i])
    print(turmas[i]['horario'])
  
for i in range(len(turmas)):
    #salaTemp = s.get()
    turmaTemp = t.get()
    for j in range(len(turmaTemp['horario'])):                                                 
        dia = turmaTemp['horario'][j][0]
        horario = turmaTemp['horario'][j][1]
        encontraMelhorSala(turmaTemp,dia,horario, salas, matriz)
        #matriz[dia][horario] = 1 
for i in range(6):
    print(matriz[i])

73
[(2, 1), (5, 3)]
[(3, 5), (5, 3)]
[(7, 1), (7, 3)]
[(3, 6)]
[(5, 6)]
[(6, 6)]
[(2, 4)]
[(4, 4)]
[(3, 7), (5, 7), (6, 7)]
[(3, 9), (5, 9)]
[(2, 5), (5, 5)]
[(2, 6), (4, 6)]
[(2, 6), (4, 6)]
[(4, 8), (6, 8)]
[(3, 3), (5, 1)]
[(3, 8), (5, 8)]
[(2, 8), (4, 8)]
[(2, 4), (4, 4), (6, 4)]
[(3, 6), (5, 6)]
[(3, 1), (4, 1)]
[(3, 1), (5, 1)]
[(2, 5), (4, 5), (6, 5)]
[(3, 7), (5, 7), (6, 7)]
[(2, 6), (4, 6)]
[(2, 3), (4, 3), (6, 1)]
[(3, 5), (5, 5)]
[(2, 3), (4, 3), (6, 3)]
[(3, 4), (5, 4), (6, 4)]
[(3, 6), (5, 6)]
[(2, 8)]
[(2, 6), (4, 6), (6, 6)]
[(3, 8), (5, 8)]
[(2, 9), (4, 9)]
[(2, 8), (4, 8), (6, 8)]
[(2, 7), (4, 7)]
[(2, 8), (4, 8)]
[(2, 7), (4, 7)]
[(3, 4), (5, 4)]
[(2, 5), (4, 5), (6, 5)]
[(3, 8), (5, 8)]
[(3, 3), (4, 5)]
[(2, 9), (4, 9), (6, 9)]
[(3, 9), (5, 9)]
[(3, 6), (5, 6)]
[(2, 1), (4, 1)]
[[2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2